In [16]:
from numpy.typing import ArrayLike
from typing import List, Union

import itertools

import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

from nn import nn, io, preprocess
from sklearn.model_selection import train_test_split
%load_ext autoreload
%autoreload 2

In [2]:
positive_examples = io.read_text_file('data/rap1-lieb-positives.txt')
negative_examples = io.read_fasta_file('data/yeast-upstream-1k-negative.fa')

In [17]:
layers = [{"input_dim": 3, "output_dim": 1, "activation": "relu"}]
net = nn.NeuralNetwork(nn_arch=layers,
                           lr=0.1,
                           seed=42,
                           batch_size=1,
                           epochs=1,
                           loss_function="mse")
print(net._param_dict)

{'W1': array([[ 0.04967142, -0.01382643,  0.06476885]]), 'b1': array([[0.15230299]])}


In [22]:
net.predict(1)

array([[0.2019744 ],
       [0.13847656],
       [0.21707184]])

In [21]:
0.04967142 + 0.15230299

0.20197441

In [37]:
W_curr = np.array([[1,2,3]])
Z_curr = np.array([[1]])
b_curr = np.array([[2]])
A_prev = np.array([[1,2,3]])
dA_curr = np.array([[1]])

In [38]:
net._single_backprop(W_curr, b_curr, Z_curr, A_prev, dA_curr, "relu")

(array([[1., 2., 3.]]), array([[1., 2., 3.]]), array([[1.]]))

In [29]:
dA_prev

array([[1., 2., 3.]])

In [46]:
net = nn.NeuralNetwork(nn_arch = [{"input_dim": 3, "output_dim": 1, "activation": "relu"}],
                           lr = 0.1,
                           seed = 0,
                           batch_size = 1,
                           epochs = 1,
                           loss_function = "mse")

print(net._param_dict)
output, cache = net.forward(np.array([0, 0, 0]))

{'W1': array([[0.17640523, 0.04001572, 0.0978738 ]]), 'b1': array([[0.22408932]])}


In [49]:
lr_grid = [1e-4, 1e-5, 1e-6]
batch_grid = [10, 50, 500]
epochs_grid = [5, 10, 20]

comb_array = np.array(np.meshgrid(lr_grid, batch_grid, epochs_grid)).T.reshape(-1, 3)
layers = [{"input_dim": 68, "output_dim": 34, "activation": "sigmoid"},
          {"input_dim": 34, "output_dim": 17, "activation": "sigmoid"},
          {"input_dim": 17, "output_dim": 1, "activation": "sigmoid"},]

# Need to reshape the y values in order to fit through net
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

NameError: name 'y_train' is not defined

In [50]:
len(comb_array)

27